name = "tyl-www"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "www.trackyourlabs.com", custom_domain = true }
]

[assets]
binding = "ASSETS"
directory = "./dist"

# Environment variables
[vars]
ENVIRONMENT = "production"
# These will be set as secrets in Cloudflare dashboard
# GCP_LAB_EXTRACT_API_KEY = "set-in-dashboard"
# GCP_LAB_EXTRACT_API_GATEWAY_URL = "set-in-dashboard"

# Observability
[observability.logs]
enabled = true