name = "tyl-www"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# CPU limits - 5 minutes (300 seconds) for paid plan
limits = { cpu_ms = 300000 }

routes = [
  { pattern = "www.trackyourlabs.com", custom_domain = true }
]

[assets]
binding = "ASSETS"
directory = "./dist"

# Environment variables
[vars]
ENVIRONMENT = "production"
# These will be set as secrets in Cloudflare dashboard
# GCP_LAB_EXTRACT_API_KEY = "set-in-dashboard"
# GCP_LAB_EXTRACT_API_GATEWAY_URL = "set-in-dashboard"

# KV Namespaces
[[kv_namespaces]]
binding = "METRICS"
id = "185d0c5e3911496fb27594d932a5dcdb"
preview_id = "a81fa5b2a0204ce085c8638c2f268027"

# Rate Limiting Configuration
# Rate limiting is implemented via Cloudflare WAF rules configured in the dashboard.
# See CLOUDFLARE_WAF_RATE_LIMITING.md for configuration details.
# WAF provides edge-level protection without requiring application code.

# Observability
[observability.logs]
enabled = true